apiVersion: v1
kind: Pod
metadata:
  name: nginx3
spec:
  containers:
  - name: nginx3
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations:
   - key: "key1"
     value: "value1"
     effect: "NoSchedule"