apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-1
spec:
  containers:
  - name: demo-container
    image: nginx
    env:
    - name: Username
      valueFrom:   
        secretKeyRef:   
          name: db-secret1
          key: username

#kubectl create secret generic db-secret --from-literal=username=dbuser --from-literal=password=Y4nys7f11
#kubectl get secret
#kubectl describe secret db-secret
#kubectl exec -it secret-demo-1 -- printenv